# Generated by Django 6.0.3 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
