# Generated by Django 5.2.12 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='target_type',
            field=models.CharField(blank=True, default='shop', max_length=50),
        ),
    ]
