# Generated by Django 5.2.12 on 2026-04-10 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_delivery_history_and_tracking(apps, schema_editor):
    Order = apps.get_model("shop", "Order")
    OrderHistory = apps.get_model("shop", "OrderHistory")
    OrderTrackingEvent = apps.get_model("shop", "OrderTrackingEvent")
    status_labels = {
        "order_placed": "Order Placed",
        "preparing_bouquet": "Preparing Bouquet",
        "out_for_delivery": "Out for Delivery",
        "delivered": "Delivered",
    }

    for order in Order.objects.all().iterator():
        OrderHistory.objects.filter(source_order_id=order.id).update(
            delivery_date=order.delivery_date,
            delivery_slot=order.delivery_slot,
            same_day_delivery=order.same_day_delivery,
            gift_message=order.gift_message,
            occasion=order.occasion,
            delivery_status=order.delivery_status,
        )

        if not OrderTrackingEvent.objects.filter(order_id=order.id).exists():
            OrderTrackingEvent.objects.create(
                order_id=order.id,
                status=order.delivery_status,
                title=status_labels.get(order.delivery_status, "Order update"),
                description="Tracking started for this floral order.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_feedback_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, choices=[('morning', '10:00 AM - 12:00 PM'), ('afternoon', '1:00 PM - 3:00 PM'), ('evening', '4:00 PM - 6:00 PM')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('preparing_bouquet', 'Preparing Bouquet'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='order_placed', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('thank_you', 'Thank You'), ('just_because', 'Just Because')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='same_day_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_slot',
            field=models.CharField(blank=True, choices=[('morning', '10:00 AM - 12:00 PM'), ('afternoon', '1:00 PM - 3:00 PM'), ('evening', '4:00 PM - 6:00 PM')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('preparing_bouquet', 'Preparing Bouquet'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='order_placed', max_length=30),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='gift_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('thank_you', 'Thank You'), ('just_because', 'Just Because')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='same_day_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('preparing_bouquet', 'Preparing Bouquet'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shop.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(backfill_delivery_history_and_tracking, migrations.RunPython.noop),
    ]
