# Generated by Django 6.0.3 on 2026-06-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_legacy_order_id'),
        ('shop', '0013_userprofile'),
    ]

    operations = [
    ]
